// import { builder,json,withAppearanceConditions,withArmor,withBlockSelectorTool,withBlockType,withBuilderTool,withCategories,withClipsGeometry,withConsumable,withContainer,withDeployablePreview,withDropOnDeath,withDurabilityLoss,withFuel,withGlider,withHUDStats,withIcon,withInteractionConfig,withInteractions,withInteractionVars,withItemEntity,withItemLevel,withItemSoundSet,withMaxDurability,withMaxStack,withPickupSound,withPlayerAnimations,withPortalKey,withPullback,withQuality,withRendering,withResourceTypes,withReticle,withSet,withTool,withTranslation,withUtility,withVariant,withWeapon,type ItemCfg } from "@";

// export const item = builder((cfg: ItemCfg, globals) =>
//   json(`${globals.paths.item.json}/${cfg.id}`, [
//     withTranslation(cfg),
//     withIcon(cfg),
//     withCategories(cfg),
//     withMaxStack(cfg),
//     withQuality(cfg),
//     withSet(cfg),
//     withItemLevel(cfg),
//     withPlayerAnimations(cfg),
//     withRendering(cfg),
//     withItemEntity(cfg),
//     withPickupSound(cfg),
//     withItemSoundSet(cfg),
//     withMaxDurability(cfg),
//     withDurabilityLoss(cfg),
//     withFuel(cfg),
//     withVariant(cfg),
//     withConsumable(cfg),
//     withDropOnDeath(cfg),
//     withClipsGeometry(cfg),
//     withDeployablePreview(cfg),
//     withTool(cfg),
//     withWeapon(cfg),
//     withArmor(cfg),
//     withGlider(cfg),
//     withUtility(cfg),
//     withBlockType(cfg),
//     withResourceTypes(cfg),
//     withInteractions(cfg),
//     withInteractionConfig(cfg),
//     withInteractionVars(cfg),
//     withAppearanceConditions(cfg),
//     withHUDStats(cfg),
//     withPullback(cfg),
//     withReticle(cfg),
//     withBlockSelectorTool(cfg),
//     withBuilderTool(cfg),
//     withPortalKey(cfg),
//     withContainer(cfg)
//   ])
// );
