import { type AutoComplete, type HasCommon, type HasGroup, type HasId, type HasLang, type Tab, type Vector3d } from "@";

// =======================================================
// Common
// =======================================================
export type HasOut = {
  out?: { json: string | { root: string }; texture: string | { root: string } };
};

/** Horizontal pixel offset. Positive moves right. */
type OffsetX = number;
/** Vertical pixel offset. Positive moves down. */
type OffsetY = number;

/** Horizontal and vertical pixel offsets. */
type Vector2d = [OffsetX, OffsetY];

/** Custom display properties for icon rendering in UI. */
export interface AssetIconProperties {
  /** Scale multiplier. 1.0 is default size. */
  scale?: number;
  /** Horizontal and vertical pixel offsets [x, y]. */
  translation?: Vector2d;
  /** Rotation in degrees around each axis [x, y, z]. */
  rotation?: Vector3d;
}

/** Icon generated by the asset editor */
export type HasAssetIcon = {
  icon?: string;
  iconGenerated?: boolean;
  iconProperties?: AssetIconProperties;
};

/** A list of categories this item will be shown in on the creative library menu. */
export type HasCategories = { categories?: Tab[] };

/** Use to sort items into a hierarchy of where an item is in progression */
export type HasItemLevel = { level?: number };

/** The maximum amount this item can be stacked in the inventory */
export type HasMaxStack = { stackSize?: number };

/** What quality to associate with the item */
export type HasItemQuality = { quality?: AutoComplete<"common" | "epic" | "legendary" | "rare" | "uncommon"> };

/** Configuration for item behavior when dropped on the ground as an entity. */
export type HasItemEntity = {
  itemEntity?: {
    physics?: {
      /** Physics mass. Affects fall speed and inertia. */
      mass?: number;
      /** Friction coefficient when sliding on surfaces (0–1 typical). */
      friction?: number;
      /** Whether gravity affects the dropped item. */
      applyGravity?: boolean;
    };
    /**
     * Distance in blocks at which a player can pick up the dropped item.
     * @default 1.75
     */
    pickupRadius?: number;
    /** Seconds before item despawns if not picked up. */
    lifetime?: number;
    /**
     * Particle system asset displayed around dropped item.
     * @default "Item"
     */
    particleSystemId?: string;
    /** Hex color for particles (`#RRGGBB`). */
    particleColor?: string;
    /**
     * Whether to show particles around dropped items.
     * @default true
     */
    showItemParticles?: boolean;
  };
};

/** Whether to drop item on death */
export type HasDropOnDeath = { dropOnDeath?: boolean };

/** Sound effect played when the item is picked up. */
export type HasPickupSound = { pickupSound?: string };

/**
 * Sound set covering all item interactions e.g. equipping, using.
 * @default "ISS_Default"
 */
export type HasItemSoundSet = { soundSet?: string };

/** Asset set this item belongs to. Groups related items for inheritance e.g. `"Tool_Iron"`. */
export type HasSet = { set?: string };

/** Path to the 3D model asset used when held or dropped, e.g. `"Items/Rock"`. */
export type HasModel = { model?: string };

/** Scale multiplier for the item model. @default 1.0 */
export type HasScale = { scale?: number };

/** Path to the texture applied to the 3D model surface. @default "Items/Unknown.png" */
export type HasTexture = {
  texture?: string;
  mask?: string;
  baseMask?: string;
  out?: string | { root: string };
  color?: string;
};

/** Animation that loops while the item is held in first or third person. */
export type HasAnimation = { animation?: string };

/**
 * When true, player hand animations drive the item display
 * instead of the item's own animations.
 * @default false
 */
export type HasUsePlayerAnimations = { usePlayerAnimations?: boolean };

/**
 * Animation set for how the player holds the item e.g. `"Sword"`, `"Pickaxe"`, `"Bow"`.
 * Controls hand position and stance when equipped.
 * @default "Default"
 */
export type HasPlayerAnimationsId = { playerAnimationsId?: string };

/** Animation played on the dropped item entity while it sits on the ground. */
export type HasDroppedItemAnimation = { droppedItemAnimation?: string };

/** Particle effects displayed around the item while held. Visible in first and third person. */
export type HasParticles = { particles?: object[] };

/** Particle effects visible only in first-person view, not to other players. */
export type HasFirstPersonParticles = { firstPersonParticles?: object[] };

/** Trail effects that follow the item model e.g. energy trails or smoke. */
export type HasTrails = { trails?: object[] };

/** RGB + brightness light emitted by the held or dropped item. */
export type HasLight = {
  light?: {
    /** Red channel (0–255). */
    red?: number;
    /** Green channel (0–255). */
    green?: number;
    /** Blue channel (0–255). */
    blue?: number;
    /** Light intensity (0–15). 15 is maximum brightness. */
    brightness?: number;
  };
};

/**
 * Map of entity stat names to appearance condition arrays.
 * Changes item appearance based on player stats e.g. at certain health thresholds.
 */
export type HasItemAppearanceConditions = { itemAppearanceConditions?: Record<string, object[]> };

/** Controls how the item behaves near walls and obstacles in first-person view. */
export type HasGeometryBehavior = {
  geometry?: {
    /**
     * When true, the item model clips through walls instead of pulling back.
     * @default false
     */
    clipsThrough?: boolean;
    /** Distance in blocks at which the arm begins to pull back near obstacles. */
    pullbackDistance?: number;
    /** Speed of the pullback animation. */
    pullbackSpeed?: number;
  };
};

/**
 * Entity stat names shown in the HUD when this item is equipped
 * e.g. `["Damage", "AttackSpeed"]`.
 */
export type HasHud = { hud?: string[] };

/**
 * Map of state names to item references or inline item definitions.
 * Used to define different states an item can be in e.g. Lit/Unlit for a torch.
 */
export type HasState = {
  state?: Record<string, string | ThingCfg> | null;
};

export type HasRendering = HasModel &
  HasScale &
  HasTexture &
  HasAnimation &
  HasUsePlayerAnimations &
  HasPlayerAnimationsId &
  HasDroppedItemAnimation &
  HasParticles &
  HasFirstPersonParticles &
  HasTrails &
  HasLight &
  HasItemAppearanceConditions &
  HasGeometryBehavior &
  HasHud &
  HasState;

/** Resources this item provides when harvested. Each entry has an id and optional quantity. */
export type HasResourceTypes = {
  resourceTypes?: { id: string; quantity?: number }[];
};

/** Whether this item is hidden from the creative menu by default. Used for connected block variants. */
export type HasVariant = { variant?: true };

export type HasInteractions = {
  /**
   * Map of interaction type to interaction asset ID e.g. `{ Primary: "my_interaction" }`.
   * Defines what happens on primary/secondary use.
   */
  interactions?: Record<string, string>;
  /**
   * Key/value pairs passed as data context to interaction scripts.
   * Allows configuring interaction behavior without separate assets.
   */
  interactionVars?: Record<string, string>;

  /** Global interaction settings. */
  disabled?: boolean;
};

export type CommonThingCfg = HasCommon &
  HasId &
  HasGroup &
  HasOut &
  HasAssetIcon &
  HasCategories &
  HasLang &
  HasMaxStack &
  HasItemQuality &
  HasItemLevel &
  HasItemEntity &
  HasSet &
  HasRendering &
  HasPickupSound &
  HasItemSoundSet &
  HasResourceTypes &
  HasDropOnDeath &
  HasVariant &
  HasInteractions;

// =======================================================
// Specialized
// =======================================================
export type HasDurability = {
  /** Maximum durability points before the item breaks. */
  maxDurability?: number;
  /** Durability consumed per hit or use. */
  durabilityLossOnHit?: number;
};

/** Tool-specific gathering configuration. */
export type HasTool = {
  tool?: {
    /** Per-material tool specifications defining power and gather type. */
    specs?: {
      /** Resource type this spec applies to e.g. `"Rocks"`, `"Wood"`. */
      gatherType: string;
      /** Effectiveness on this gather type. Higher = faster and more efficient. */
      power: number;
      /** Quality level of this tool spec. Higher quality gathers better resources. */
      quality?: number;
      /** Whether this tool is incorrect for the material. Gathers slower or not at all. */
      isIncorrect?: boolean;
      /** Sound effect when hitting this block type. */
      hitSoundLayer?: string;
    }[];
    /** Speed multiplier for tool usage. @default 1.0 */
    speed?: number;
    /** Per-material durability loss settings. */
    durabilityLossBlockTypes?: {
      /** Specific block type IDs that cause durability loss. */
      blockTypes?: string[];
      /** Block set identifiers that cause durability loss. */
      blockSets?: string[];
      /** Durability consumed per hit on specified blocks. */
      durabilityLossOnHit?: number;
    }[];
    /** Default sound when tool hits blocks. Plays in addition to block breaking sound. */
    hitCorrectSound?: string;
    /** Sound played when tool hits an incorrect material. */
    hitIncorrectSound?: string;
  };
};
export type ToolCfg = CommonThingCfg & HasTool & HasDurability;

export type HasBlockSelectorTool = {
  /** Block selector tool config. Allows players to select blocks in the world. */
  blockSelectorTool?: {
    durabilityLossOnUse: number;
  };
};
export type BlockSelectorToolCfg = CommonThingCfg & HasBlockSelectorTool;

export type HasBuilderTool = {
  /** Builder tool config for brushes and placers. Enables building and terraforming. */
  builderTool?: {
    ui: string[];
    UI: {
      type: ["array", "null"];
      hytale: {
        type: "array";
      };
      items: {
        type: "string";
        hytale: {
          type: "string";
        };
      };
    };
    Tools: {
      type: "array";
      hytale: {
        type: "array";
      };
      items: {
        properties: {
          Parent: {
            type: "string";
            description: "When set this asset will inherit properties from the named asset.\n\nWhen inheriting from another BuilderTool most properties will simply be copied from the parent asset to this asset. In the case where both child and parent provide a field the child field will simply replace the value provided by the parent, in the case of nested structures this will apply to the fields within the structure. In some cases the field may decide to act differently, for example: by merging the parent and child fields together.";
            markdownDescription: "When set this asset will inherit properties from the named asset.\n\nWhen inheriting from another **BuilderTool** most properties will simply be copied from the parent asset to this asset. In the case where both child and parent provide a field the child field will simply replace the value provided by the parent, in the case of nested structures this will apply to the fields within the structure. In some cases the field may decide to act differently, for example: by merging the parent and child fields together.";
            hytaleParent: {
              type: "BuilderTool";
            };
            hytale: {
              type: "string";
            };
          };
          Tags: {
            type: ["object", "null"];
            title: "Map";
            description: "Tags are a general way to describe an asset that can be interpreted by other systems in a way they see fit.\n\nFor example you could tag something with a Material tag with the values Solid and Stone, And another single tag Ore.\n\nTags will be expanded into a single list of tags automatically. Using the above example with Material and Ore the end result would be the following list of tags: Ore, Material, Solid, Stone, Material=Solid and Material=Stone.";
            markdownDescription: "Tags are a general way to describe an asset that can be interpreted by other systems in a way they see fit.\n\nFor example you could tag something with a **Material** tag with the values **Solid** and **Stone**, And another single tag **Ore**.\n\nTags will be expanded into a single list of tags automatically. Using the above example with **Material** and **Ore** the end result would be the following list of tags: **Ore**, **Material**, **Solid**, **Stone**, **Material=Solid** and **Material=Stone**.";
            hytale: {
              type: "object";
              inheritsProperty: true;
            };
            additionalProperties: {
              type: "array";
              hytale: {
                type: "array";
              };
              items: {
                type: "string";
                hytale: {
                  type: "string";
                };
              };
            };
          };
          Id: {
            type: ["string", "null"];
            hytale: {
              type: "string";
            };
          };
          IsBrush: {
            type: "boolean";
            hytale: {
              type: "boolean";
            };
            default: false;
          };
          BrushConfigurationCommand: {
            type: ["string", "null"];
            hytale: {
              type: "string";
            };
          };
          Args: {
            type: ["object", "null"];
            title: "Map";
            hytale: {
              type: "object";
            };
            additionalProperties: {
              title: "Type Selector";
              anyOf: [
                {
                  $ref: "common.json#/definitions/BlockArg";
                },
                {
                  $ref: "common.json#/definitions/BoolArg";
                },
                {
                  $ref: "common.json#/definitions/BrushOriginArg";
                },
                {
                  $ref: "common.json#/definitions/BrushShapeArg";
                },
                {
                  $ref: "common.json#/definitions/FloatArg";
                },
                {
                  $ref: "common.json#/definitions/IntArg";
                },
                {
                  $ref: "common.json#/definitions/MaskArg";
                },
                {
                  $ref: "common.json#/definitions/OptionArg";
                },
                {
                  $ref: "common.json#/definitions/StringArg";
                }
              ];
              hytaleSchemaTypeField: {
                property: "Type";
                values: ["Block", "Bool", "BrushOrigin", "BrushShape", "Float", "Int", "Mask", "Option", "String"];
              };
              hytale: {
                mergesProperties: true;
              };
            };
          };
          BrushData: {
            anyOf: [
              {
                default: {
                  Width: {
                    Required: true;
                    Default: 5;
                    Min: 1;
                    Max: 100;
                  };
                  Height: {
                    Required: true;
                    Default: 5;
                    Min: 1;
                    Max: 100;
                  };
                  Thickness: {
                    Required: true;
                    Default: 0;
                    Min: 0;
                    Max: 100;
                  };
                  Capped: {
                    Required: true;
                    Default: false;
                  };
                  Shape: {
                    Required: true;
                    Default: "Sphere";
                  };
                  Origin: {
                    Required: true;
                    Default: "Center";
                  };
                  OriginRotation: {
                    Required: true;
                    Default: false;
                  };
                  RotationAxis: {
                    Required: true;
                    Default: "None";
                  };
                  RotationAngle: {
                    Required: true;
                    Default: "None";
                  };
                  MirrorAxis: {
                    Required: true;
                    Default: "None";
                  };
                  Material: {
                    Required: true;
                    Default: "Empty";
                    AllowPattern: true;
                  };
                  FavoriteMaterials: [];
                  Mask: {
                    Required: false;
                    Default: "-";
                  };
                  MaskAbove: {
                    Required: false;
                    Default: "-";
                  };
                  MaskNot: {
                    Required: false;
                    Default: "-";
                  };
                  MaskBelow: {
                    Required: false;
                    Default: "-";
                  };
                  MaskAdjacent: {
                    Required: false;
                    Default: "-";
                  };
                  MaskNeighbor: {
                    Required: false;
                    Default: "-";
                  };
                  MaskCommands: [];
                  UseMaskCommands: {
                    Required: true;
                    Default: false;
                  };
                  InvertMask: {
                    Required: true;
                    Default: false;
                  };
                };
                $ref: "common.json#/definitions/BrushData";
              },
              {
                type: "null";
              }
            ];
          };
        };
      };
      minItems: 1;
    };
  };
};
export type BuilderToolCfg = CommonThingCfg & HasBuilderTool;

/** Custom aiming reticle displayed when the item is aimed. */
export type HasReticle = {
  reticle?: {
    /** Size of the aiming reticle. */
    size?: number;
    /** Hex color of the reticle (`#RRGGBB`). */
    color?: string;
  };
};

/** Weapon-specific combat configuration. */
export type HasWeapon = {
  weapon?: {
    /** Entity stat modifications applied when weapon is equipped e.g. Damage, AttackSpeed. */
    statModifiers?: Record<string, StaticModifier[]>;
    /** Entity stats to remove when weapon is unequipped. */
    entityStatsToClear?: string[];
    /** Whether this weapon renders in both hands when equipped. */
    duelWielded?: boolean;
  };
};
export type WeaponCfg = CommonThingCfg & HasWeapon & HasDurability & HasReticle;

type Cosmetic =
  | "Haircut"
  | "FacialHair"
  | "Undertop"
  | "Overtop"
  | "Pants"
  | "Overpants"
  | "Shoes"
  | "Gloves"
  | "Cape"
  | "HeadAccessory"
  | "FaceAccessory"
  | "EarAccessory"
  | "Ear";

/** Armor-specific protection configuration. */
export type HasArmor = {
  armor?: {
    /** Which equipment slot this armor occupies. */
    slot?: "Head" | "Chest" | "Hands" | "Legs";
    /** Base damage reduction as a fraction. 0.2 = 20% reduction. */
    baseDamageResistance?: number;
    /** Per-damage-type resistance modifiers. */
    resistance?: Record<string, StaticModifier[]>;
    /** Per-damage-type enhancement modifiers. */
    enhancement?: Record<string, StaticModifier[]>;
    /** Per-damage-type knockback resistance values. */
    knockbackResistances?: Record<string, number>;
    /** Entity stat modifications when armor is equipped. */
    statModifiers?: Record<string, StaticModifier[]>;
    regenerating?: {
      Interval: {
        anyOf: [
          {
            anyOf: [
              {
                type: "number";
                hytale: {
                  type: "number";
                };
                default: 0.0;
              },
              {
                type: "string";
                hytale: {
                  type: "string";
                };
                pattern: "^(-?Infinity|NaN)$";
              }
            ];
            hytale: {
              type: "Number";
            };
          },
          {
            type: "null";
          }
        ];
      };
      Amount: {
        anyOf: [
          {
            anyOf: [
              {
                type: "number";
                hytale: {
                  type: "number";
                };
                default: 0.0;
              },
              {
                type: "string";
                hytale: {
                  type: "string";
                };
                pattern: "^(-?Infinity|NaN)$";
              }
            ];
            hytale: {
              type: "Number";
            };
          },
          {
            type: "null";
          }
        ];
      };
      ClampAtZero: {
        type: "boolean";
        description: "Prevents this regenerating value from taking the stat value below zero.";
        markdownDescription: "Prevents this regenerating value from taking the stat value below zero.";
        hytale: {
          type: "boolean";
        };
        default: false;
      };
      RegenType: {
        type: ["string", "null"];
        title: "RegenType";
        enumDescriptions: ["", ""];
        markdownEnumDescriptions: ["", ""];
        hytale: {
          type: "Enum";
        };
        enum: ["Additive", "Percentage"];
      };
      Conditions: {
        type: ["array", "null"];
        hytale: {
          type: "array";
        };
        items: {
          title: "Type Selector";
          anyOf: [
            {
              $ref: "common.json#/definitions/AliveCondition";
            },
            {
              $ref: "common.json#/definitions/ChargingCondition";
            },
            {
              $ref: "common.json#/definitions/EnvironmentCondition";
            },
            {
              $ref: "common.json#/definitions/GlidingCondition";
            },
            {
              $ref: "common.json#/definitions/LogicCondition";
            },
            {
              $ref: "common.json#/definitions/NoDamageTakenCondition";
            },
            {
              $ref: "common.json#/definitions/OutOfCombatCondition";
            },
            {
              $ref: "common.json#/definitions/PlayerCondition";
            },
            {
              $ref: "common.json#/definitions/RegenHealthCondition";
            },
            {
              $ref: "common.json#/definitions/SprintingCondition";
            },
            {
              $ref: "common.json#/definitions/StatCondition";
            },
            {
              $ref: "common.json#/definitions/SuffocatingCondition";
            },
            {
              $ref: "common.json#/definitions/WieldingCondition";
            }
          ];
          hytaleSchemaTypeField: {
            property: "Id";
            values: [
              "Alive",
              "Charging",
              "Environment",
              "Gliding",
              "LogicCondition",
              "NoDamageTaken",
              "OutOfCombat",
              "Player",
              "RegenHealth",
              "Sprinting",
              "Stat",
              "Suffocating",
              "Wielding"
            ];
          };
          hytale: {
            mergesProperties: true;
          };
        };
      };
      Modifiers: {
        type: ["array", "null"];
        hytale: {
          type: "array";
        };
        items: {
          Conditions: {
            type: ["array", "null"];
            hytale: {
              type: "array";
            };
            items: {
              title: "Type Selector";
              anyOf: [
                {
                  $ref: "common.json#/definitions/AliveCondition";
                },
                {
                  $ref: "common.json#/definitions/ChargingCondition";
                },
                {
                  $ref: "common.json#/definitions/EnvironmentCondition";
                },
                {
                  $ref: "common.json#/definitions/GlidingCondition";
                },
                {
                  $ref: "common.json#/definitions/LogicCondition";
                },
                {
                  $ref: "common.json#/definitions/NoDamageTakenCondition";
                },
                {
                  $ref: "common.json#/definitions/OutOfCombatCondition";
                },
                {
                  $ref: "common.json#/definitions/PlayerCondition";
                },
                {
                  $ref: "common.json#/definitions/RegenHealthCondition";
                },
                {
                  $ref: "common.json#/definitions/SprintingCondition";
                },
                {
                  $ref: "common.json#/definitions/StatCondition";
                },
                {
                  $ref: "common.json#/definitions/SuffocatingCondition";
                },
                {
                  $ref: "common.json#/definitions/WieldingCondition";
                }
              ];
              hytaleSchemaTypeField: {
                property: "Id";
                values: [
                  "Alive",
                  "Charging",
                  "Environment",
                  "Gliding",
                  "LogicCondition",
                  "NoDamageTaken",
                  "OutOfCombat",
                  "Player",
                  "RegenHealth",
                  "Sprinting",
                  "Stat",
                  "Suffocating",
                  "Wielding"
                ];
              };
              hytale: {
                mergesProperties: true;
              };
            };
          };
          Amount: {
            anyOf: [
              {
                anyOf: [
                  {
                    type: "number";
                    hytale: {
                      type: "number";
                    };
                    default: 0.0;
                  },
                  {
                    type: "string";
                    hytale: {
                      type: "string";
                    };
                    pattern: "^(-?Infinity|NaN)$";
                  }
                ];
                hytale: {
                  type: "Number";
                };
              },
              {
                type: "null";
              }
            ];
          };
        };
      };
    };
    /** Cosmetic items hidden when this armor is equipped to prevent clipping. */
    hide: Cosmetic[];
  };
};
export type ArmorCfg = CommonThingCfg & HasArmor & HasDurability;

/** Glider flight physics configuration. */
export type HasGlider = {
  glider?: {
    fallSpeed: {
      /** The rate at which the fall speed is incremented. */
      multiplier: number;
      /** Maximum fall speed while gliding. */
      max: number;
    };
    speed: {
      /** The rate at which the horizontal move speed is incremented. */
      multiplier: number;
      /** The horizontal movement speed of the glider. */
      speed: number;
    };
  };
};

export type GliderCfg = CommonThingCfg & HasGlider;

export type StaticModifier = {
  /** string in the format
   * +10 - Additive, Max, 10
   * -10 - Additive, Max, -10
   * *1.5 - Multiplicative, Max, 1.5
   * +10min - Additive, Min, 10
   * *1.5min - Multiplicative, Min, 1.5
   */
  modifier?: string;
};

/** Utility item configuration for usable/compatible items. */
export type HasUtility = {
  utility?: {
    /** Whether this item can be activated/used by the player. */
    usable?: boolean;
    /** Whether this item is compatible with other items for combination effects. */
    compatible?: boolean;
    /** Entity stat modifications while item is held. */
    statModifiers?: Record<string, StaticModifier[]>;
    /** Entity stats to remove when item is unequipped. */
    entityStatsToClear?: string[];
  };
};
export type UtilityCfg = CommonThingCfg & HasUtility;

export type HasPortalKey = {
  /** Portal key config for fast travel / teleportation mechanics. */
  portalKey?: {
    /** The ID of of the PortalType that this key opens. */
    id: string;
    /** Time limit for being inside the portal. default to -1 or infinite */
    timeLimit?: number;
  };
};
export type PortalKeyCfg = CommonThingCfg & HasPortalKey;

export type HasContainer = {
  /** Container config enabling this item to store other items. */
  container?: {
    capacity: number;
    filter: "AllowInputOnly" | "AllowOutputOnly" | "AllowAll" | "DenyAll";
    tag?: string;
  };
};
export type ContainerCfg = CommonThingCfg & HasContainer;

/** Marks item as consumed/used up on activation. */
export type HasConsumable = { consumable?: boolean };
export type ConsumableCfg = CommonThingCfg & HasConsumable;

/** How good of a fuel source this item is. Higher values burn longer. @default 1.0 */
export type HasFuelQuality = { fuelQuality?: number };
export type FuelCfg = CommonThingCfg & HasFuelQuality;

/** Block-type item configuration for items that can be placed in the world. */
export type HasBlockType = {
  blockType?: {
    /** Block group for categorization e.g. `"Stone"`, `"Wood"`. `"@Tech"` prevents auto physics. */
    group?: string;
    /** Physical material. `"Empty"` = non-solid, `"Solid"` = blocks movement. */
    material?: "Empty" | "Solid";
    /** Rendering method. */
    drawType?: "Empty" | "GizmoCube" | "Cube" | "Model" | "CubeWithModel";
    /** Transparency level affecting rendering and light propagation. */
    opacity?: "Solid" | "Transparent" | "Translucent";
    /**
     * Textures for block faces. Multiple entries enable random variants via weight.
     * Use `all` for a single texture on all faces, or specify per-face textures.
     */
    textures?: {
      all?: string;
      up?: string;
      down?: string;
      north?: string;
      south?: string;
      east?: string;
      west?: string;
      /** Weight for random variant selection. Higher = selected more often. */
      weight?: number;
    }[];
    /** Path to custom 3D model. Used when drawType is `"Model"` or `"CubeWithModel"`. */
    customModel?: string;
    /** Scale multiplier for the custom model. @default 1.0 */
    customModelScale?: number;
    /** Animation asset for the custom model e.g. flowing water or lava. */
    customModelAnimation?: string;
    /** Hex color for block interaction particles (`#RRGGBB`). */
    particleColor?: string;
    /** Particle system spawned on block interaction (stepping, breaking, using). */
    blockParticleSetId?: string;
    /** Sound set for block placement, breaking, and interaction. @default "EMPTY" */
    blockSoundSetId?: string;
    /** Decal overlay showing damage progression while block is being broken. */
    blockBreakingDecalId?: string;
    /** Light emitted by the block. */
    light?: {
      red?: number;
      green?: number;
      blue?: number;
      /** Light intensity (0–15). 15 is maximum brightness. */
      brightness?: number;
    };
    flags?: {
      /** Whether the block can be interacted with. */
      isUsable?: boolean;
      /** Whether multiple blocks can occupy the same space. */
      isStackable?: boolean;
    };
    gathering?: {
      breaking?: {
        /** Resource type gathered e.g. `"Rocks"`, `"Wood"`. Determines valid tools. */
        gatherType?: string;
        /** Item ID that drops when the block is broken. */
        itemId?: string;
        /** Number of items dropped per break. */
        quantity?: number;
      };
    };
  };
};

export type HasRenderDeployablePreview = { renderPreview?: boolean };
export type BlockCfg = CommonThingCfg & HasBlockType & HasRenderDeployablePreview;

export type ThingCfg = CommonThingCfg &
  ToolCfg &
  BlockSelectorToolCfg &
  BuilderToolCfg &
  WeaponCfg &
  ArmorCfg &
  GliderCfg &
  UtilityCfg &
  PortalKeyCfg &
  ContainerCfg &
  ConsumableCfg &
  FuelCfg &
  BlockCfg;
