export const reactiveNonmetals: MaterialConfig[] = [
  { id: "hydrogen", config: { color: "#B2EBF2" } },
  { id: "helium", config: { color: "#FFF9C4" } },
  { id: "carbon", config: { color: "#37474F" } },
  { id: "nitrogen", config: { color: "#C5CAE9" } },
  { id: "oxygen", config: { color: "#EF9A9A" } },
  { id: "fluorine", config: { color: "#E6EE9C" } },
  { id: "neon", config: { color: "#FFAB91" } },
  { id: "phosphorus", config: { color: "#FFCC80" } },
  { id: "sulfur", config: { color: "#FFF176" } },
  { id: "chlorine", config: { color: "#CCFF90" } },
  { id: "argon", config: { color: "#D1C4E9" } },
  { id: "selenium", config: { color: "#80CBC4" } },
  { id: "bromine", config: { color: "#A5D6A7" } },
  { id: "krypton", config: { color: "#81D4FA" } },
  { id: "iodine", config: { color: "#CE93D8" } },
  { id: "xenon", config: { color: "#90CAF9" } },
  { id: "astatine", config: { color: "#8D6E63" } },
  { id: "radon", config: { color: "#BCAAA4" } },
  { id: "tennessine", config: { color: "#4DB6AC" } },
  { id: "oganesson", config: { color: "#CFD8DC" } },
];

export const alkaliMetals: MaterialConfig[] = [
  { id: "lithium", config: { color: "#FF5252" } },
  { id: "sodium", config: { color: "#FFD740" } },
  { id: "potassium", config: { color: "#E040FB" } },
  { id: "rubidium", config: { color: "#FF4081" } },
  { id: "caesium", config: { color: "#7C4DFF" } },
  { id: "francium", config: { color: "#B71C1C" } },
];

export const alkalineEarthMetals: MaterialConfig[] = [
  { id: "beryllium", config: { color: "#4CAF50" } },
  { id: "magnesium", config: { color: "#8BC34A" } },
  { id: "calcium", config: { color: "#CDDC39" } },
  { id: "strontium", config: { color: "#FFEB3B" } },
  { id: "barium", config: { color: "#FFC107" } },
  { id: "radium", config: { color: "#FF9800" } },
];

export const transitionMetals: MaterialConfig[] = [
  { id: "scandium", config: { color: "#00BCD4" } },
  { id: "titanium", config: { color: "#03A9F4" } },
  { id: "vanadium", config: { color: "#2196F3" } },
  { id: "chromium", config: { color: "#3F51B5" } },
  { id: "manganese", config: { color: "#673AB7" } },
  { id: "iron", config: { color: "#9C27B0" } },
  { id: "cobalt", config: { color: "#E91E63" } },
  { id: "nickel", config: { color: "#F44336" } },
  { id: "copper", config: { color: "#FF5722" } },
  { id: "zinc", config: { color: "#FF9800" } },
  { id: "yttrium", config: { color: "#FFC107" } },
  { id: "zirconium", config: { color: "#FFEB3B" } },
  { id: "niobium", config: { color: "#CDDC39" } },
  { id: "molybdenum", config: { color: "#8BC34A" } },
  { id: "technetium", config: { color: "#4CAF50" } },
  { id: "ruthenium", config: { color: "#009688" } },
  { id: "rhodium", config: { color: "#00BCD4" } },
  { id: "palladium", config: { color: "#03A9F4" } },
  { id: "silver", config: { color: "#B0BEC5" } },
  { id: "cadmium", config: { color: "#FF8A80" } },
  { id: "hafnium", config: { color: "#FF5252" } },
  { id: "tantalum", config: { color: "#E040FB" } },
  { id: "tungsten", config: { color: "#7C4DFF" } },
  { id: "rhenium", config: { color: "#536DFE" } },
  { id: "osmium", config: { color: "#448AFF" } },
  { id: "iridium", config: { color: "#40C4FF" } },
  { id: "platinum", config: { color: "#E0E0E0" } },
  { id: "gold", config: { color: "#FFD700" } },
  { id: "mercury", config: { color: "#CFD8DC" } },
  { id: "rutherfordium", config: { color: "#F06292" } },
  { id: "dubnium", config: { color: "#BA68C8" } },
  { id: "seaborgium", config: { color: "#9575CD" } },
  { id: "bohrium", config: { color: "#7986CB" } },
  { id: "hassium", config: { color: "#64B5F6" } },
  { id: "meitnerium", config: { color: "#4FC3F7" } },
  { id: "darmstadtium", config: { color: "#4DB6AC" } },
  { id: "roentgenium", config: { color: "#81C784" } },
  { id: "copernicium", config: { color: "#AED581" } },
];

export const postTransitionMetals: MaterialConfig[] = [
  { id: "aluminum", config: { color: "#90A4AE" } },
  { id: "gallium", config: { color: "#DCE775" } },
  { id: "indium", config: { color: "#4DD0E1" } },
  { id: "tin", config: { color: "#9575CD" } },
  { id: "thallium", config: { color: "#A1887F" } },
  { id: "lead", config: { color: "#455A64" } },
  { id: "bismuth", config: { color: "#FF80AB" } },
  { id: "nihonium", config: { color: "#FFB74D" } },
  { id: "flerovium", config: { color: "#FFD54F" } },
  { id: "moscovium", config: { color: "#BA68C8" } },
  { id: "livermorium", config: { color: "#81C784" } },
];

export const metalloids: MaterialConfig[] = [
  { id: "boron", config: { color: "#8D6E63" } },
  { id: "silicon", config: { color: "#78909C" } },
  { id: "germanium", config: { color: "#9E9E9E" } },
  { id: "arsenic", config: { color: "#D4E157" } },
  { id: "antimony", config: { color: "#CE93D8" } },
  { id: "tellurium", config: { color: "#F48FB1" } },
  { id: "polonium", config: { color: "#FFF176" } },
];

export const lanthanides: MaterialConfig[] = [
  { id: "lanthanum", config: { color: "#E1F5FE" } },
  { id: "cerium", config: { color: "#B3E5FC" } },
  { id: "praseodymium", config: { color: "#81D4FA" } },
  { id: "neodymium", config: { color: "#4FC3F7" } },
  { id: "promethium", config: { color: "#29B6F6" } },
  { id: "samarium", config: { color: "#039BE5" } },
  { id: "europium", config: { color: "#0288D1" } },
  { id: "gadolinium", config: { color: "#0277BD" } },
  { id: "terbium", config: { color: "#01579B" } },
  { id: "dysprosium", config: { color: "#E8EAF6" } },
  { id: "holmium", config: { color: "#C5CAE9" } },
  { id: "erbium", config: { color: "#9FA8DA" } },
  { id: "thulium", config: { color: "#7986CB" } },
  { id: "ytterbium", config: { color: "#5C6BC0" } },
  { id: "lutetium", config: { color: "#3F51B5" } },
];

export const actinides: MaterialConfig[] = [
  { id: "actinium", config: { color: "#FCE4EC" } },
  { id: "thorium", config: { color: "#F8BBD0" } },
  { id: "protactinium", config: { color: "#F48FB1" } },
  { id: "uranium", config: { color: "#F06292" } },
  { id: "neptunium", config: { color: "#EC407A" } },
  { id: "plutonium", config: { color: "#D81B60" } },
  { id: "americium", config: { color: "#AD1457" } },
  { id: "curium", config: { color: "#880E4F" } },
  { id: "berkelium", config: { color: "#E1BEE7" } },
  { id: "californium", config: { color: "#D1C4E9" } },
  { id: "einsteinium", config: { color: "#B39DDB" } },
  { id: "fermium", config: { color: "#9575CD" } },
  { id: "mendelevium", config: { color: "#7E57C2" } },
  { id: "nobelium", config: { color: "#673AB7" } },
  { id: "lawrencium", config: { color: "#512DA8" } },
];

export const elements: MaterialConfig[] = [
  ...reactiveNonmetals,
  ...alkaliMetals,
  ...alkalineEarthMetals,
  ...transitionMetals,
  ...postTransitionMetals,
  ...metalloids,
  ...lanthanides,
  ...actinides,
];
